### ISSUE TITLE
systemd service require mysql-wait-ready

### ISSUE THREAD

**Issue by hilyjiang** [iuscommunity-pkg/mysql57u#5]
According to ExecStartPost in mysql.service.in:
```
ExecStartPost=@libexecdir@/mysql-wait-ready $MAINPID
```
systemd service also require mysql-wait-ready.

So mysql-wait-ready should also install in systemd system.

Wrong defines in spec:
```
# install SysV init script
%if %{with init_sysv}
install -D -p -m 755 scripts/mysql.init %{buildroot}%{daemondir}/%{daemon_name}
install -p -m 755 scripts/mysql-wait-ready %{buildroot}%{_libexecdir}/mysql-wait-ready
%endif
```
```
%if %{with init_sysv}
%{_libexecdir}/mysql-wait-ready
%endif
```

**Comment by carlwgeorge** [comment]
The systemd parts of our spec file were carried over when we forked from Fedora's community-mysql spec file.  We only ship mysql57u for EL6, so we haven't bothered testing/using the systemd parts.  It appears that Fedora resolved this by [removing that ExecStartPost line from their unit file](https://src.fedoraproject.org/cgit/rpms/community-mysql.git/diff/mysql.service.in?id=199818834576d6bbcded5d6e842dc161fe4061a6).  At some point we will probably import that change when we sync our package with community-mysql again, but since we are not shipping systemd mysql57u packages anywhere it isn't a high priority.

**Comment by hilyjiang** [comment]
Thanks carlwgeorge.

I have merged mysql.service.in from Fedora and rebuild the package, and now it works.
