### ISSUE TITLE
unable to input utf8 characters in the mysql client

### ISSUE THREAD

**Issue by gotyaoi** [iuscommunity-pkg/mysql57u#7]
Attempting to input certain non-ascii characters in the mysql client is behaving in rather odd ways. For example, trying to input "J’ai" results in "aiJ", with the cursor positioned after the "i". Trying to input the word "consommé" silently declines to input the "é", leaving "consomm". There is other such strangeness. It doesn't seem to be a problem with character set or collation mismatches, as "select" statements produce these characters to the terminal with no problem, and statements run from a file with "source" can send these characters to the server. I located this possibly related issue in the redhat bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=1187469

where it seems they traced it down to the switch from readline to libedit. I was able to reproduce the issue from that ticket exactly.

**Comment by b-harper** [comment]
Hey @gotyaoi,

Thanks for contacting us about this issue.  Before we look too much into this issue, can you confirm some details first.

When you say 'mysql client' are you referring to the cli client and not something like a php or python module?

Can you provide a list of all installed  mysql packages and versions?

Can you provide the locale information?

**Comment by gotyaoi** [comment]
Sure. The issue only presents when typing or pasting into the mysql cli. All programmatic access works correctly, including running pre-written sql files through the cli, like `$ mysql < foo.sql` and `mysql> source foo.sql`

mysql package versions are as follows:
```
mysql57u-common-5.7.19-1.ius.centos6.x86_64
mysql57u-config-5.7.19-1.ius.centos6.x86_64
mysqlclient16-5.1.61-4.ius.centos6.x86_64
mysql57u-5.7.19-1.ius.centos6.x86_64
```

locale information is as follows:
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

charset and collation information is as follows:
```
mysql> SHOW VARIABLES LIKE 'character_set%';
+--------------------------+-------------------------------------------+
| Variable_name            | Value                                     |
+--------------------------+-------------------------------------------+
| character_set_client     | utf8                                      |
| character_set_connection | utf8                                      |
| character_set_database   | utf8                                      |
| character_set_filesystem | binary                                    |
| character_set_results    | utf8                                      |
| character_set_server     | latin1                                    |
| character_set_system     | utf8                                      |
| character_sets_dir       | /rdsdbbin/mysql-5.7.11.R1/share/charsets/ |
+--------------------------+-------------------------------------------+
8 rows in set (0.00 sec)

mysql> SHOW VARIABLES LIKE 'collation%';
+----------------------+-------------------+
| Variable_name        | Value             |
+----------------------+-------------------+
| collation_connection | utf8_general_ci   |
| collation_database   | utf8_general_ci   |
| collation_server     | latin1_swedish_ci |
+----------------------+-------------------+
3 rows in set (0.00 sec)
```

**Comment by b-harper** [comment]
Thanks for the additional information.  I just wanted to make sure you were running the latest packages.  

First I must admit, I am not a DBA or mysql expert.  Over the years, character sets within mysql server/clients have given me plenty of head aches.  I know there is a trade off when it comes to different line editing libraries.  It always seems to be a trade off of features (like search) and better character support.  

Can I assume you do not run into this issue when using the corresponding Unicode escape sequence?  I ran into something like this when troubleshooting the pile of poo emoji:


```
mysql> INSERT INTO table_name(column_name) VALUES ('\U+1F4A9');

Query OK, 1 row affected (0.00 sec)

 

mysql> select * from table_name;

+-------------+

| column_name |

+-------------+

| yolo        |

| 💩            |

+-------------+

2 rows in set (0.00 sec)

 

mysql> INSERT INTO table_name(column_name) VALUES ('𝌆');

Query OK, 1 row affected (0.00 sec)

 

mysql> select * from table_name;

+-------------+

| column_name |

+-------------+

| yolo        |

| 💩            |

| 𝌆            |

+-------------+

3 rows in set (0.00 sec)
```

**Comment by gotyaoi** [comment]
I don't seem to have the \U escape sequence in the cli. Attempting to insert "\U+00E9" just inserts the literal string "U+00E9". same for "\U+1F4A9", just gets "U+1F4A9". Can't find anything about \U in the docs either... https://dev.mysql.com/doc/refman/5.7/en/string-literals.html

**Comment by b-harper** [comment]
Now that I think about it,  Unicode escape sequences really does not have anything to do this issue.  Tricking the mysql cli client by using alternative input methods is at best a work around.  Note, emojis need the utf8mb4 character set.

In the past, I have run into issues with text rich apostrophes being shown as �.  It appears you are using a text rich apostrophe.  Do you still have this issue with a plain text apostrophe, like "    '    " (spacing for easy copy/paste)?  

I was able to verify if your  "é" is the same character from a [UTF-8 list][2]:

```
$ #copy/paste from github issue
$ echo 'é' |md5sum 
88df14e6957d2adb8ae54d0269f546ab  -

$#copy/paste from UTF-8 list
$ echo 'é' |md5sum
88df14e6957d2adb8ae54d0269f546ab  -
```
Our mysql57u packages are forked from Fedora.  We are using the same method for [line editing][0] as [Fedora][1].   I would be curious if this issue is happening on Fedora too.



[0]: https://github.com/iuscommunity-pkg/mysql57u/blob/98988b4e1317fba1877dcaecc96eeb0659c7e4ff/SPECS/mysql57u.spec#L557
[1]: https://src.fedoraproject.org/rpms/community-mysql/blob/61b324e26e2030d8bdeea716e78cd166ada77d8d/f/community-mysql.spec#_514
[2]: http://www.utf8-chartable.de/

**Comment by b-harper** [comment]
Now that I think about it,  Unicode escape sequences really does not have anything to do this issue.  Tricking the mysql cli client by using alternative input methods is at best a work around.  Note, emojis need the utf8mb4 character set.

In the past, I have run into issues with text rich apostrophes being shown as �.  It appears you are using a text rich apostrophe.  Do you still have this issue with a plain text apostrophe, like "    '    " (spacing for easy copy/paste)?  

I was able to verify if your  "é" is the same character from a [UTF-8 list][2]:

```
$ #copy/paste from github issue
$ echo 'é' |md5sum 
88df14e6957d2adb8ae54d0269f546ab  -

$#copy/paste from UTF-8 list
$ echo 'é' |md5sum
88df14e6957d2adb8ae54d0269f546ab  -
```
Our mysql57u packages are forked from Fedora.  We are using the same method for [line editing][0] as [Fedora][1].   I would be curious if this issue is happening on Fedora too.



[0]: https://github.com/iuscommunity-pkg/mysql57u/blob/98988b4e1317fba1877dcaecc96eeb0659c7e4ff/SPECS/mysql57u.spec#L557
[1]: https://src.fedoraproject.org/rpms/community-mysql/blob/61b324e26e2030d8bdeea716e78cd166ada77d8d/f/community-mysql.spec#_514
[2]: http://www.utf8-chartable.de/

**Comment by gotyaoi** [comment]
No, no issues with typing an ascii apostrophe.

The link I posted above to the redhat bugzilla was in relation to fedora. Going through the other issues linked from that one led me to this one: https://bugzilla.redhat.com/show_bug.cgi?id=1202022#c2, where they seem to have fixed the issue by altering the libedit packaged by fedora. Centos6 looks to be on 2.11, while fedora is on 3.1.

I'm not sure if this occurs on Centos7, which is on libedit 3.0, as I don't have a suitable machine to test at the moment.

**Comment by b-harper** [comment]
Hey @gotyaoi,

It does appear that EL7 is not effected as I was able to do the following with the stock mariadb packages:

```
# mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2
Server version: 5.5.56-MariaDB MariaDB Server

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> create database yolo;
Query OK, 1 row affected (0.00 sec)
MariaDB [yolo]> CREATE TABLE table_name ( column_name TEXT CHARACTER SET utf8 );
Query OK, 0 rows affected (0.00 sec)
MariaDB [yolo]> INSERT INTO table_name(column_name) VALUES ('J’ai');
Query OK, 1 row affected (0.01 sec)
MariaDB [yolo]> INSERT INTO table_name(column_name) VALUES ('consommé');
Query OK, 1 row affected (0.00 sec)
MariaDB [yolo]> select * from table_name;
+-------------+
| column_name |
+-------------+
| J’ai        |
| consommé    |
+-------------+
2 rows in set (0.00 sec)
```

**Comment by gotyaoi** [comment]
Ok, so given the status of el6, I assume this is wontfix?

We're migrating, but it's slow T_T.

edit: I just looked into it and mariadb apparently bundles readline statically, instead of linking to the system version of either readline or libedit.

**Comment by carlwgeorge** [comment]
Sorry for the delay in getting back to you on this.  You're right, EL6 is late in it's lifecycle, and I'm afraid we don't have the resources to dig in further (as I'm sure you've assumed by now).  If someone figures out the solution I'd be happy to review and merge a pull request.

For what it's worth, the recently released [mariadb102](https://github.com/iusrepo/mariadb102) for EL7 is not affected by this bug.  I'd recommend migrating to that if you can.
